name: Daily Python Script

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run Daily Tasks
        run: |
          python src/jobs.py  --freq=daily  
