name: Monthly Python Script

on:
  schedule:
    # Runs on the first day of every month at midnight UTC
    - cron: '0 0 1 * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt if you have one

      - name: Run Python script
        run: |
          python src/jobs.py --freq=monthly
